CONSOLE_ENABLE   = yes
MOUSEKEY_ENABLE  = yes
# TAP_DANCE_ENABLE = yes
COMMAND_ENABLE   = no
BOOTMAGIC_ENABLE = yes
NKRO_ENABLE      = yes
UNICODE_ENABLE   = yes

AUDIO_ENABLE     = no
API_SYSEX_ENABLE = no
