CONSOLE_ENABLE   = yes
MOUSEKEY_ENABLE  = yes
TAP_DANCE_ENABLE = yes
COMMAND_ENABLE   = yes
NKRO_ENABLE      = no
AUDIO_ENABLE     = no
UNICODE_ENABLE   = no
BOOTMAGIC_ENABLE = no
API_SYSEX_ENABLE = no

EXTRAFLAGS      += -flto
